### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by BOC111** [tiki/website#1]
### Reason

We need a privacy policy

### Description

This is a boiler plate Privacy Policy

### Success Criteria

- [x] Policy posted to the Tiki Website

### Additional Information

Last Updated: [Today's Date]

1. ### 1.  Introduction

Welcome to Tiki (hereinafter referred to as "we," "us," or "our"). At Tiki, we value your privacy and are committed to protecting your personal information. This Privacy Policy outlines how we collect, use, disclose, and safeguard your information when you visit our website or use our services.

By accessing or using MyTiki.com, you agree to the terms and practices described in this Privacy Policy. Please read this policy carefully to understand our practices regarding your personal information. If you do not agree with this policy, please do not use our website or services.

### 2. Information We Collect

We collect both personally identifiable information (PII) and non-personally identifiable information when you interact with our website or use our services. The types of information we collect include:

**2.1. Personal Information**: This may include your name, email address, phone number, and other information you provide when you register for an account or contact us.

**2.2. Log Data:** When you visit our website, our servers automatically collect information such as your IP address, browser type, device type, operating system, and other technical details.

**2.3 Cookies and Similar Technologies**: We may use cookies, web beacons, and other tracking technologies to collect information about your browsing behaviour and preferences.

**2.4 User Content**: Any content you voluntarily submit to our website, such as comments, reviews, or other user-generated content.

###3. How we store your information
We store three types of information.

**3.1 Information generated by the Tiki SDK**:This is information recorded and stored if you accept an offer made by a third-party company in return for a form of compensation (detail here https://mytiki.com/docs/sdk-overview).

**3.2 The information described in 2 above**

**3.3 Information shared by a third party**: In the course of our business we may have third-party data or aggregated data shared with us by third parties for the purposes of selling these insights. In the normal course of these transactions, data will be shared containing an identifier that may identify the user. 

Your consent to share or sell your data is entirely voluntary, and you have the right to refuse or withdraw this consent at any time without facing adverse consequences.

We will always seek your permission before sharing or selling your data for commercial purposes and will clearly explain the purposes and entities involved in each specific instance.

### 3. How We Use Your Information

We use the information we collect for various purposes, including:

**3.1. Providing Services**: To provide you with the services you request, including account registration, personalized content, and customer support.

**3.2. Improving Our Services**: To analyze and improve our website, content, and user experience.

**3.3 Communication**: To send you updates, newsletters, and promotional materials. You can opt-out of marketing communications at any time.

**3.4 Legal Compliance**: To comply with legal obligations and respond to legal requests.

### 4. Data Storage and Commercial Use with User Permission

We value your privacy and are committed to maintaining the highest standards of data protection. In certain instances, with your explicit and informed consent, we may share or sell your data to trusted third parties for commercial purposes. This may include sharing your information with carefully selected partners, advertisers, or other entities for marketing, research, or other commercial activities.

Your consent to share or sell your data is entirely voluntary, and you have the right to refuse or withdraw this consent at any time without facing adverse consequences. We will always seek your permission before sharing or selling your data for commercial purposes and will clearly explain the purposes and entities involved in each specific instance.

Before providing your consent, we strongly recommend that you review the terms and conditions, privacy policies, and data handling practices of any third parties involved in these transactions. Your data's security remains a top priority for us, and we will take all reasonable measures to ensure its protection during any commercial transactions.

### 5. Your Choices

**5.1. Access and Correction**: You can access and edit your account information through your profile settings. You can also request access to your personal information and correct any inaccuracies.

**5.2. Opt-Out**: You can opt out of receiving marketing communications from us by following the instructions provided in the communication.

### 6. Security

We employ reasonable security measures to protect your personal information. However, no data transmission or storage can be guaranteed to be 100% secure. Please understand that you provide your information at your own risk.

###  7. Children's Privacy

Our website and services are not intended for children under the age of 16. We do not knowingly collect or solicit personal information from children. If we learn that we have collected personal information from a child under 16, we will take steps to delete it.

### 8. Changes to this Privacy Policy

We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational, legal, or regulatory reasons. We will post the updated Privacy Policy on our website with the "Last Updated" date. Your continued use of our website after any changes indicates your acceptance of the revised Privacy Policy.

### 9. Contact Us

If you have any questions, concerns, or requests regarding this Privacy Policy or your personal information, please contact us at contact@mytiki.com.

Thank you for choosing Tiki. Your privacy is important to us.

[End of Privacy Policy]

**Comment by mike-audi** [comment]
@sfaria27 @BOC111 

please review: https://mytiki.com/page/privacy

**Comment by BOC111** [comment]
That is quite different to the one I wrote.......

It looks good to me.
