### ISSUE TITLE
Table + button should not add the table to the query

### ISSUE THREAD

**Issue by mike-audi** [tiki/website#22]
### Reason

Make it easier to find the columns without screwing up your query

### Description

The button expands the column list, so if you're just looking for what you need it screws up your query

### Success Criteria

- [ ] The + button does not add the table to the query.

**Comment by timoguin** [comment]
Agreed. Clicking a column in the list will also paste it onto the end of your query. We should remove both of these features for now. In a future iteration, we can explore adding back in a more explicit way, where it is intentional from the user.

Moved this into the "Todo" status.
